namespace MentorLake.HarfBuzz;

[Flags]
public enum hb_buffer_cluster_level_t
{
	HB_BUFFER_CLUSTER_LEVEL_MONOTONE_GRAPHEMES = 0,
	HB_BUFFER_CLUSTER_LEVEL_MONOTONE_CHARACTERS = 1,
	HB_BUFFER_CLUSTER_LEVEL_CHARACTERS = 2,
	HB_BUFFER_CLUSTER_LEVEL_DEFAULT = 0
}
