namespace MentorLake.HarfBuzz;

[Flags]
public enum hb_buffer_serialize_flags_t : uint
{
	HB_BUFFER_SERIALIZE_FLAG_DEFAULT = 0,
	HB_BUFFER_SERIALIZE_FLAG_NO_CLUSTERS = 1,
	HB_BUFFER_SERIALIZE_FLAG_NO_POSITIONS = 2,
	HB_BUFFER_SERIALIZE_FLAG_NO_GLYPH_NAMES = 4,
	HB_BUFFER_SERIALIZE_FLAG_GLYPH_EXTENTS = 8,
	HB_BUFFER_SERIALIZE_FLAG_GLYPH_FLAGS = 16,
	HB_BUFFER_SERIALIZE_FLAG_NO_ADVANCES = 32,
	HB_BUFFER_SERIALIZE_FLAG_DEFINED = 63
}
