namespace MentorLake.HarfBuzz;

[Flags]
public enum hb_ot_layout_glyph_class_t
{
	HB_OT_LAYOUT_GLYPH_CLASS_UNCLASSIFIED = 0,
	HB_OT_LAYOUT_GLYPH_CLASS_BASE_GLYPH = 1,
	HB_OT_LAYOUT_GLYPH_CLASS_LIGATURE = 2,
	HB_OT_LAYOUT_GLYPH_CLASS_MARK = 3,
	HB_OT_LAYOUT_GLYPH_CLASS_COMPONENT = 4
}
