namespace MentorLake.HarfBuzz;

[Flags]
public enum hb_paint_composite_mode_t
{
	HB_PAINT_COMPOSITE_MODE_CLEAR = 0,
	HB_PAINT_COMPOSITE_MODE_SRC = 1,
	HB_PAINT_COMPOSITE_MODE_DEST = 2,
	HB_PAINT_COMPOSITE_MODE_SRC_OVER = 3,
	HB_PAINT_COMPOSITE_MODE_DEST_OVER = 4,
	HB_PAINT_COMPOSITE_MODE_SRC_IN = 5,
	HB_PAINT_COMPOSITE_MODE_DEST_IN = 6,
	HB_PAINT_COMPOSITE_MODE_SRC_OUT = 7,
	HB_PAINT_COMPOSITE_MODE_DEST_OUT = 8,
	HB_PAINT_COMPOSITE_MODE_SRC_ATOP = 9,
	HB_PAINT_COMPOSITE_MODE_DEST_ATOP = 10,
	HB_PAINT_COMPOSITE_MODE_XOR = 11,
	HB_PAINT_COMPOSITE_MODE_PLUS = 12,
	HB_PAINT_COMPOSITE_MODE_SCREEN = 13,
	HB_PAINT_COMPOSITE_MODE_OVERLAY = 14,
	HB_PAINT_COMPOSITE_MODE_DARKEN = 15,
	HB_PAINT_COMPOSITE_MODE_LIGHTEN = 16,
	HB_PAINT_COMPOSITE_MODE_COLOR_DODGE = 17,
	HB_PAINT_COMPOSITE_MODE_COLOR_BURN = 18,
	HB_PAINT_COMPOSITE_MODE_HARD_LIGHT = 19,
	HB_PAINT_COMPOSITE_MODE_SOFT_LIGHT = 20,
	HB_PAINT_COMPOSITE_MODE_DIFFERENCE = 21,
	HB_PAINT_COMPOSITE_MODE_EXCLUSION = 22,
	HB_PAINT_COMPOSITE_MODE_MULTIPLY = 23,
	HB_PAINT_COMPOSITE_MODE_HSL_HUE = 24,
	HB_PAINT_COMPOSITE_MODE_HSL_SATURATION = 25,
	HB_PAINT_COMPOSITE_MODE_HSL_COLOR = 26,
	HB_PAINT_COMPOSITE_MODE_HSL_LUMINOSITY = 27
}
