namespace MentorLake.GdkPixbuf;

[Flags]
public enum GdkPixbufError
{
	GDK_PIXBUF_ERROR_CORRUPT_IMAGE = 0,
	GDK_PIXBUF_ERROR_INSUFFICIENT_MEMORY = 1,
	GDK_PIXBUF_ERROR_BAD_OPTION = 2,
	GDK_PIXBUF_ERROR_UNKNOWN_TYPE = 3,
	GDK_PIXBUF_ERROR_UNSUPPORTED_OPERATION = 4,
	GDK_PIXBUF_ERROR_FAILED = 5,
	GDK_PIXBUF_ERROR_INCOMPLETE_ANIMATION = 6
}
