namespace MentorLake.Vulkan;

public class VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXTHandle : BaseSafeHandle
{
}


public static class VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXTExtensions
{

	public static VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT Dereference(this VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXTHandle x) => System.Runtime.InteropServices.Marshal.PtrToStructure<VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT>(x.DangerousGetHandle());
}
internal class VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXTExterns
{
}

public struct VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT
{
}
