namespace MentorLake.Gtk;

[Flags]
public enum GtkBuilderError
{
	GTK_BUILDER_ERROR_INVALID_TYPE_FUNCTION = 0,
	GTK_BUILDER_ERROR_UNHANDLED_TAG = 1,
	GTK_BUILDER_ERROR_MISSING_ATTRIBUTE = 2,
	GTK_BUILDER_ERROR_INVALID_ATTRIBUTE = 3,
	GTK_BUILDER_ERROR_INVALID_TAG = 4,
	GTK_BUILDER_ERROR_MISSING_PROPERTY_VALUE = 5,
	GTK_BUILDER_ERROR_INVALID_VALUE = 6,
	GTK_BUILDER_ERROR_VERSION_MISMATCH = 7,
	GTK_BUILDER_ERROR_DUPLICATE_ID = 8,
	GTK_BUILDER_ERROR_OBJECT_TYPE_REFUSED = 9,
	GTK_BUILDER_ERROR_TEMPLATE_MISMATCH = 10,
	GTK_BUILDER_ERROR_INVALID_PROPERTY = 11,
	GTK_BUILDER_ERROR_INVALID_SIGNAL = 12,
	GTK_BUILDER_ERROR_INVALID_ID = 13
}
