namespace MentorLake.Gtk;

[Flags]
public enum GtkBorderStyle
{
	GTK_BORDER_STYLE_NONE = 0,
	GTK_BORDER_STYLE_SOLID = 1,
	GTK_BORDER_STYLE_INSET = 2,
	GTK_BORDER_STYLE_OUTSET = 3,
	GTK_BORDER_STYLE_HIDDEN = 4,
	GTK_BORDER_STYLE_DOTTED = 5,
	GTK_BORDER_STYLE_DASHED = 6,
	GTK_BORDER_STYLE_DOUBLE = 7,
	GTK_BORDER_STYLE_GROOVE = 8,
	GTK_BORDER_STYLE_RIDGE = 9
}
