namespace MentorLake.Gtk;

[Flags]
public enum GtkCssProviderError
{
	GTK_CSS_PROVIDER_ERROR_FAILED = 0,
	GTK_CSS_PROVIDER_ERROR_SYNTAX = 1,
	GTK_CSS_PROVIDER_ERROR_IMPORT = 2,
	GTK_CSS_PROVIDER_ERROR_NAME = 3,
	GTK_CSS_PROVIDER_ERROR_DEPRECATED = 4,
	GTK_CSS_PROVIDER_ERROR_UNKNOWN_VALUE = 5
}
