namespace MentorLake.Gtk;

[Flags]
public enum GtkCellRendererState : long
{
	GTK_CELL_RENDERER_SELECTED = 1,
	GTK_CELL_RENDERER_PRELIT = 2,
	GTK_CELL_RENDERER_INSENSITIVE = 4,
	GTK_CELL_RENDERER_SORTED = 8,
	GTK_CELL_RENDERER_FOCUSED = 16,
	GTK_CELL_RENDERER_EXPANDABLE = 32,
	GTK_CELL_RENDERER_EXPANDED = 64
}
