namespace MentorLake.Gtk;

[Flags]
public enum GtkCssSectionType
{
	GTK_CSS_SECTION_DOCUMENT = 0,
	GTK_CSS_SECTION_IMPORT = 1,
	GTK_CSS_SECTION_COLOR_DEFINITION = 2,
	GTK_CSS_SECTION_BINDING_SET = 3,
	GTK_CSS_SECTION_RULESET = 4,
	GTK_CSS_SECTION_SELECTOR = 5,
	GTK_CSS_SECTION_DECLARATION = 6,
	GTK_CSS_SECTION_VALUE = 7,
	GTK_CSS_SECTION_KEYFRAMES = 8
}
