namespace MentorLake.Gtk;

[Flags]
public enum GtkDragResult
{
	GTK_DRAG_RESULT_SUCCESS = 0,
	GTK_DRAG_RESULT_NO_TARGET = 1,
	GTK_DRAG_RESULT_USER_CANCELLED = 2,
	GTK_DRAG_RESULT_TIMEOUT_EXPIRED = 3,
	GTK_DRAG_RESULT_GRAB_BROKEN = 4,
	GTK_DRAG_RESULT_ERROR = 5
}
