namespace MentorLake.Gtk;

[Flags]
public enum GtkFileChooserConfirmation
{
	GTK_FILE_CHOOSER_CONFIRMATION_CONFIRM = 0,
	GTK_FILE_CHOOSER_CONFIRMATION_ACCEPT_FILENAME = 1,
	GTK_FILE_CHOOSER_CONFIRMATION_SELECT_AGAIN = 2
}
