namespace MentorLake.Gtk;

[Flags]
public enum GtkFileChooserError
{
	GTK_FILE_CHOOSER_ERROR_NONEXISTENT = 0,
	GTK_FILE_CHOOSER_ERROR_BAD_FILENAME = 1,
	GTK_FILE_CHOOSER_ERROR_ALREADY_EXISTS = 2,
	GTK_FILE_CHOOSER_ERROR_INCOMPLETE_HOSTNAME = 3
}
