namespace MentorLake.Gtk;

[Flags]
public enum GtkIconLookupFlags : long
{
	GTK_ICON_LOOKUP_NO_SVG = 1,
	GTK_ICON_LOOKUP_FORCE_SVG = 2,
	GTK_ICON_LOOKUP_USE_BUILTIN = 4,
	GTK_ICON_LOOKUP_GENERIC_FALLBACK = 8,
	GTK_ICON_LOOKUP_FORCE_SIZE = 16,
	GTK_ICON_LOOKUP_FORCE_REGULAR = 32,
	GTK_ICON_LOOKUP_FORCE_SYMBOLIC = 64,
	GTK_ICON_LOOKUP_DIR_LTR = 128,
	GTK_ICON_LOOKUP_DIR_RTL = 256
}
