namespace MentorLake.Gtk;

[Flags]
public enum GtkInputPurpose
{
	GTK_INPUT_PURPOSE_FREE_FORM = 0,
	GTK_INPUT_PURPOSE_ALPHA = 1,
	GTK_INPUT_PURPOSE_DIGITS = 2,
	GTK_INPUT_PURPOSE_NUMBER = 3,
	GTK_INPUT_PURPOSE_PHONE = 4,
	GTK_INPUT_PURPOSE_URL = 5,
	GTK_INPUT_PURPOSE_EMAIL = 6,
	GTK_INPUT_PURPOSE_NAME = 7,
	GTK_INPUT_PURPOSE_PASSWORD = 8,
	GTK_INPUT_PURPOSE_PIN = 9,
	GTK_INPUT_PURPOSE_TERMINAL = 10
}
