namespace MentorLake.Gtk;

[Flags]
public enum GtkIconViewDropPosition
{
	GTK_ICON_VIEW_NO_DROP = 0,
	GTK_ICON_VIEW_DROP_INTO = 1,
	GTK_ICON_VIEW_DROP_LEFT = 2,
	GTK_ICON_VIEW_DROP_RIGHT = 3,
	GTK_ICON_VIEW_DROP_ABOVE = 4,
	GTK_ICON_VIEW_DROP_BELOW = 5
}
