namespace MentorLake.Gtk;

[Flags]
public enum GtkJunctionSides : long
{
	GTK_JUNCTION_NONE = 0,
	GTK_JUNCTION_CORNER_TOPLEFT = 1,
	GTK_JUNCTION_CORNER_TOPRIGHT = 2,
	GTK_JUNCTION_CORNER_BOTTOMLEFT = 4,
	GTK_JUNCTION_CORNER_BOTTOMRIGHT = 8,
	GTK_JUNCTION_TOP = 3,
	GTK_JUNCTION_BOTTOM = 12,
	GTK_JUNCTION_LEFT = 5,
	GTK_JUNCTION_RIGHT = 10
}
