namespace MentorLake.Gtk;

[Flags]
public enum GtkLicense
{
	GTK_LICENSE_UNKNOWN = 0,
	GTK_LICENSE_CUSTOM = 1,
	GTK_LICENSE_GPL_2_0 = 2,
	GTK_LICENSE_GPL_3_0 = 3,
	GTK_LICENSE_LGPL_2_1 = 4,
	GTK_LICENSE_LGPL_3_0 = 5,
	GTK_LICENSE_BSD = 6,
	GTK_LICENSE_MIT_X11 = 7,
	GTK_LICENSE_ARTISTIC = 8,
	GTK_LICENSE_GPL_2_0_ONLY = 9,
	GTK_LICENSE_GPL_3_0_ONLY = 10,
	GTK_LICENSE_LGPL_2_1_ONLY = 11,
	GTK_LICENSE_LGPL_3_0_ONLY = 12,
	GTK_LICENSE_AGPL_3_0 = 13,
	GTK_LICENSE_AGPL_3_0_ONLY = 14,
	GTK_LICENSE_BSD_3 = 15,
	GTK_LICENSE_APACHE_2_0 = 16,
	GTK_LICENSE_MPL_2_0 = 17
}
