namespace MentorLake.Gtk;

[Flags]
public enum GtkPageOrientation
{
	GTK_PAGE_ORIENTATION_PORTRAIT = 0,
	GTK_PAGE_ORIENTATION_LANDSCAPE = 1,
	GTK_PAGE_ORIENTATION_REVERSE_PORTRAIT = 2,
	GTK_PAGE_ORIENTATION_REVERSE_LANDSCAPE = 3
}
