namespace MentorLake.Gtk;

[Flags]
public enum GtkPrintOperationAction
{
	GTK_PRINT_OPERATION_ACTION_PRINT_DIALOG = 0,
	GTK_PRINT_OPERATION_ACTION_PRINT = 1,
	GTK_PRINT_OPERATION_ACTION_PREVIEW = 2,
	GTK_PRINT_OPERATION_ACTION_EXPORT = 3
}
