namespace MentorLake.Gtk;

[Flags]
public enum GtkRecentFilterFlags : long
{
	GTK_RECENT_FILTER_URI = 1,
	GTK_RECENT_FILTER_DISPLAY_NAME = 2,
	GTK_RECENT_FILTER_MIME_TYPE = 4,
	GTK_RECENT_FILTER_APPLICATION = 8,
	GTK_RECENT_FILTER_GROUP = 16,
	GTK_RECENT_FILTER_AGE = 32
}
