namespace MentorLake.Gtk;

[Flags]
public enum GtkRecentManagerError
{
	GTK_RECENT_MANAGER_ERROR_NOT_FOUND = 0,
	GTK_RECENT_MANAGER_ERROR_INVALID_URI = 1,
	GTK_RECENT_MANAGER_ERROR_INVALID_ENCODING = 2,
	GTK_RECENT_MANAGER_ERROR_NOT_REGISTERED = 3,
	GTK_RECENT_MANAGER_ERROR_READ = 4,
	GTK_RECENT_MANAGER_ERROR_WRITE = 5,
	GTK_RECENT_MANAGER_ERROR_UNKNOWN = 6
}
