namespace MentorLake.Gtk;

[Flags]
public enum GtkRevealerTransitionType
{
	GTK_REVEALER_TRANSITION_TYPE_NONE = 0,
	GTK_REVEALER_TRANSITION_TYPE_CROSSFADE = 1,
	GTK_REVEALER_TRANSITION_TYPE_SLIDE_RIGHT = 2,
	GTK_REVEALER_TRANSITION_TYPE_SLIDE_LEFT = 3,
	GTK_REVEALER_TRANSITION_TYPE_SLIDE_UP = 4,
	GTK_REVEALER_TRANSITION_TYPE_SLIDE_DOWN = 5
}
