namespace MentorLake.Gtk;

[Flags]
public enum GtkStackTransitionType
{
	GTK_STACK_TRANSITION_TYPE_NONE = 0,
	GTK_STACK_TRANSITION_TYPE_CROSSFADE = 1,
	GTK_STACK_TRANSITION_TYPE_SLIDE_RIGHT = 2,
	GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT = 3,
	GTK_STACK_TRANSITION_TYPE_SLIDE_UP = 4,
	GTK_STACK_TRANSITION_TYPE_SLIDE_DOWN = 5,
	GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT = 6,
	GTK_STACK_TRANSITION_TYPE_SLIDE_UP_DOWN = 7,
	GTK_STACK_TRANSITION_TYPE_OVER_UP = 8,
	GTK_STACK_TRANSITION_TYPE_OVER_DOWN = 9,
	GTK_STACK_TRANSITION_TYPE_OVER_LEFT = 10,
	GTK_STACK_TRANSITION_TYPE_OVER_RIGHT = 11,
	GTK_STACK_TRANSITION_TYPE_UNDER_UP = 12,
	GTK_STACK_TRANSITION_TYPE_UNDER_DOWN = 13,
	GTK_STACK_TRANSITION_TYPE_UNDER_LEFT = 14,
	GTK_STACK_TRANSITION_TYPE_UNDER_RIGHT = 15,
	GTK_STACK_TRANSITION_TYPE_OVER_UP_DOWN = 16,
	GTK_STACK_TRANSITION_TYPE_OVER_DOWN_UP = 17,
	GTK_STACK_TRANSITION_TYPE_OVER_LEFT_RIGHT = 18,
	GTK_STACK_TRANSITION_TYPE_OVER_RIGHT_LEFT = 19
}
