namespace MentorLake.Gtk;

[Flags]
public enum GtkShortcutType
{
	GTK_SHORTCUT_ACCELERATOR = 0,
	GTK_SHORTCUT_GESTURE_PINCH = 1,
	GTK_SHORTCUT_GESTURE_STRETCH = 2,
	GTK_SHORTCUT_GESTURE_ROTATE_CLOCKWISE = 3,
	GTK_SHORTCUT_GESTURE_ROTATE_COUNTERCLOCKWISE = 4,
	GTK_SHORTCUT_GESTURE_TWO_FINGER_SWIPE_LEFT = 5,
	GTK_SHORTCUT_GESTURE_TWO_FINGER_SWIPE_RIGHT = 6,
	GTK_SHORTCUT_GESTURE = 7
}
