namespace MentorLake.Gtk;

[Flags]
public enum GtkTextBufferTargetInfo
{
	GTK_TEXT_BUFFER_TARGET_INFO_BUFFER_CONTENTS = -1,
	GTK_TEXT_BUFFER_TARGET_INFO_RICH_TEXT = -2,
	GTK_TEXT_BUFFER_TARGET_INFO_TEXT = -3
}
