namespace MentorLake.cairo;

[Flags]
public enum cairo_surface_type_t
{
	CAIRO_SURFACE_TYPE_IMAGE = 0,
	CAIRO_SURFACE_TYPE_PDF = 1,
	CAIRO_SURFACE_TYPE_PS = 2,
	CAIRO_SURFACE_TYPE_XLIB = 3,
	CAIRO_SURFACE_TYPE_XCB = 4,
	CAIRO_SURFACE_TYPE_GLITZ = 5,
	CAIRO_SURFACE_TYPE_QUARTZ = 6,
	CAIRO_SURFACE_TYPE_WIN32 = 7,
	CAIRO_SURFACE_TYPE_BEOS = 8,
	CAIRO_SURFACE_TYPE_DIRECTFB = 9,
	CAIRO_SURFACE_TYPE_SVG = 10,
	CAIRO_SURFACE_TYPE_OS2 = 11,
	CAIRO_SURFACE_TYPE_WIN32_PRINTING = 12,
	CAIRO_SURFACE_TYPE_QUARTZ_IMAGE = 13,
	CAIRO_SURFACE_TYPE_SCRIPT = 14,
	CAIRO_SURFACE_TYPE_QT = 15,
	CAIRO_SURFACE_TYPE_RECORDING = 16,
	CAIRO_SURFACE_TYPE_VG = 17,
	CAIRO_SURFACE_TYPE_GL = 18,
	CAIRO_SURFACE_TYPE_DRM = 19,
	CAIRO_SURFACE_TYPE_TEE = 20,
	CAIRO_SURFACE_TYPE_XML = 21,
	CAIRO_SURFACE_TYPE_SKIA = 22,
	CAIRO_SURFACE_TYPE_SUBSURFACE = 23,
	CAIRO_SURFACE_TYPE_COGL = 24
}
