namespace MentorLake.cairo;

[Flags]
public enum cairo_pattern_type_t
{
	CAIRO_PATTERN_TYPE_SOLID = 0,
	CAIRO_PATTERN_TYPE_SURFACE = 1,
	CAIRO_PATTERN_TYPE_LINEAR = 2,
	CAIRO_PATTERN_TYPE_RADIAL = 3,
	CAIRO_PATTERN_TYPE_MESH = 4,
	CAIRO_PATTERN_TYPE_RASTER_SOURCE = 5
}
