namespace MentorLake.cairo;

[Flags]
public enum cairo_device_type_t
{
	CAIRO_DEVICE_TYPE_DRM = 0,
	CAIRO_DEVICE_TYPE_GL = 1,
	CAIRO_DEVICE_TYPE_SCRIPT = 2,
	CAIRO_DEVICE_TYPE_XCB = 3,
	CAIRO_DEVICE_TYPE_XLIB = 4,
	CAIRO_DEVICE_TYPE_XML = 5,
	CAIRO_DEVICE_TYPE_COGL = 6,
	CAIRO_DEVICE_TYPE_WIN32 = 7,
	CAIRO_DEVICE_TYPE_INVALID = -1
}
