namespace MentorLake.Gtk3.Gdk3;

[Flags]
public enum GdkAxisFlags
{
	GDK_AXIS_FLAG_X = 0,
	GDK_AXIS_FLAG_Y = 1,
	GDK_AXIS_FLAG_PRESSURE = 2,
	GDK_AXIS_FLAG_XTILT = 4,
	GDK_AXIS_FLAG_YTILT = 8,
	GDK_AXIS_FLAG_WHEEL = 16,
	GDK_AXIS_FLAG_DISTANCE = 32,
	GDK_AXIS_FLAG_ROTATION = 64,
	GDK_AXIS_FLAG_SLIDER = 128
}
