namespace MentorLake.Gtk3.Gdk3;

public enum GdkDragProtocol
{
	GDK_DRAG_PROTO_NONE,
	GDK_DRAG_PROTO_MOTIF,
	GDK_DRAG_PROTO_XDND,
	GDK_DRAG_PROTO_ROOTWIN,
	GDK_DRAG_PROTO_WIN32_DROPFILES,
	GDK_DRAG_PROTO_OLE2,
	GDK_DRAG_PROTO_LOCAL,
	GDK_DRAG_PROTO_WAYLAND
}
