namespace MentorLake.Gtk3.Gdk3;

public enum GdkInputSource
{
	GDK_SOURCE_MOUSE,
	GDK_SOURCE_PEN,
	GDK_SOURCE_ERASER,
	GDK_SOURCE_CURSOR,
	GDK_SOURCE_KEYBOARD,
	GDK_SOURCE_TOUCHSCREEN,
	GDK_SOURCE_TOUCHPAD,
	GDK_SOURCE_TRACKPOINT,
	GDK_SOURCE_TABLET_PAD
}
