namespace MentorLake.Gtk3.Gdk3;

[Flags]
public enum GdkSeatCapabilities
{
	GDK_SEAT_CAPABILITY_NONE = 0,
	GDK_SEAT_CAPABILITY_POINTER = 1,
	GDK_SEAT_CAPABILITY_TOUCH = 2,
	GDK_SEAT_CAPABILITY_TABLET_STYLUS = 4,
	GDK_SEAT_CAPABILITY_KEYBOARD = 8,
	GDK_SEAT_CAPABILITY_ALL_POINTING = 16,
	GDK_SEAT_CAPABILITY_ALL = 32
}
