namespace MentorLake.Gtk3.Gdk3;

public enum GdkSubpixelLayout
{
	GDK_SUBPIXEL_LAYOUT_UNKNOWN,
	GDK_SUBPIXEL_LAYOUT_NONE,
	GDK_SUBPIXEL_LAYOUT_HORIZONTAL_RGB,
	GDK_SUBPIXEL_LAYOUT_HORIZONTAL_BGR,
	GDK_SUBPIXEL_LAYOUT_VERTICAL_RGB,
	GDK_SUBPIXEL_LAYOUT_VERTICAL_BGR
}
