namespace MentorLake.Gtk3.Gdk3;

public enum GdkWindowType
{
	GDK_WINDOW_ROOT,
	GDK_WINDOW_TOPLEVEL,
	GDK_WINDOW_CHILD,
	GDK_WINDOW_TEMP,
	GDK_WINDOW_FOREIGN,
	GDK_WINDOW_OFFSCREEN,
	GDK_WINDOW_SUBSURFACE
}
