namespace MentorLake.Graphene;

[Flags]
public enum graphene_euler_order_t
{
	GRAPHENE_EULER_ORDER_DEFAULT = -1,
	GRAPHENE_EULER_ORDER_XYZ = 0,
	GRAPHENE_EULER_ORDER_YZX = 1,
	GRAPHENE_EULER_ORDER_ZXY = 2,
	GRAPHENE_EULER_ORDER_XZY = 3,
	GRAPHENE_EULER_ORDER_YXZ = 4,
	GRAPHENE_EULER_ORDER_ZYX = 5,
	GRAPHENE_EULER_ORDER_SXYZ = 6,
	GRAPHENE_EULER_ORDER_SXYX = 7,
	GRAPHENE_EULER_ORDER_SXZY = 8,
	GRAPHENE_EULER_ORDER_SXZX = 9,
	GRAPHENE_EULER_ORDER_SYZX = 10,
	GRAPHENE_EULER_ORDER_SYZY = 11,
	GRAPHENE_EULER_ORDER_SYXZ = 12,
	GRAPHENE_EULER_ORDER_SYXY = 13,
	GRAPHENE_EULER_ORDER_SZXY = 14,
	GRAPHENE_EULER_ORDER_SZXZ = 15,
	GRAPHENE_EULER_ORDER_SZYX = 16,
	GRAPHENE_EULER_ORDER_SZYZ = 17,
	GRAPHENE_EULER_ORDER_RZYX = 18,
	GRAPHENE_EULER_ORDER_RXYX = 19,
	GRAPHENE_EULER_ORDER_RYZX = 20,
	GRAPHENE_EULER_ORDER_RXZX = 21,
	GRAPHENE_EULER_ORDER_RXZY = 22,
	GRAPHENE_EULER_ORDER_RYZY = 23,
	GRAPHENE_EULER_ORDER_RZXY = 24,
	GRAPHENE_EULER_ORDER_RYXY = 25,
	GRAPHENE_EULER_ORDER_RYXZ = 26,
	GRAPHENE_EULER_ORDER_RZXZ = 27,
	GRAPHENE_EULER_ORDER_RXYZ = 28,
	GRAPHENE_EULER_ORDER_RZYZ = 29
}
