namespace MentorLake.GLib;

[Flags]
public enum GBookmarkFileError
{
	G_BOOKMARK_FILE_ERROR_INVALID_URI = 0,
	G_BOOKMARK_FILE_ERROR_INVALID_VALUE = 1,
	G_BOOKMARK_FILE_ERROR_APP_NOT_REGISTERED = 2,
	G_BOOKMARK_FILE_ERROR_URI_NOT_FOUND = 3,
	G_BOOKMARK_FILE_ERROR_READ = 4,
	G_BOOKMARK_FILE_ERROR_UNKNOWN_ENCODING = 5,
	G_BOOKMARK_FILE_ERROR_WRITE = 6,
	G_BOOKMARK_FILE_ERROR_FILE_NOT_FOUND = 7
}
