namespace MentorLake.GLib;

[Flags]
public enum GConvertError
{
	G_CONVERT_ERROR_NO_CONVERSION = 0,
	G_CONVERT_ERROR_ILLEGAL_SEQUENCE = 1,
	G_CONVERT_ERROR_FAILED = 2,
	G_CONVERT_ERROR_PARTIAL_INPUT = 3,
	G_CONVERT_ERROR_BAD_URI = 4,
	G_CONVERT_ERROR_NOT_ABSOLUTE_PATH = 5,
	G_CONVERT_ERROR_NO_MEMORY = 6,
	G_CONVERT_ERROR_EMBEDDED_NUL = 7
}
