namespace MentorLake.GLib;

[Flags]
public enum GErrorType
{
	G_ERR_UNKNOWN = 0,
	G_ERR_UNEXP_EOF = 1,
	G_ERR_UNEXP_EOF_IN_STRING = 2,
	G_ERR_UNEXP_EOF_IN_COMMENT = 3,
	G_ERR_NON_DIGIT_IN_CONST = 4,
	G_ERR_DIGIT_RADIX = 5,
	G_ERR_FLOAT_RADIX = 6,
	G_ERR_FLOAT_MALFORMED = 7
}
