namespace MentorLake.GLib;

[Flags]
public enum GKeyFileError
{
	G_KEY_FILE_ERROR_UNKNOWN_ENCODING = 0,
	G_KEY_FILE_ERROR_PARSE = 1,
	G_KEY_FILE_ERROR_NOT_FOUND = 2,
	G_KEY_FILE_ERROR_KEY_NOT_FOUND = 3,
	G_KEY_FILE_ERROR_GROUP_NOT_FOUND = 4,
	G_KEY_FILE_ERROR_INVALID_VALUE = 5
}
