namespace MentorLake.GLib;

/// <summary>
/// <para>
/// Flags that affect the behaviour of the parser.
/// </para>
/// </summary>

[Flags]
public enum GMarkupParseFlags : uint
{
/// <summary>
/// <para>
/// No special behaviour. Since: 2.74
/// </para>
/// </summary>

	G_MARKUP_DEFAULT_FLAGS = 0,
/// <summary>
/// <para>
/// flag you should not use
/// </para>
/// </summary>

	G_MARKUP_DO_NOT_USE_THIS_UNSUPPORTED_FLAG = 1,
/// <summary>
/// <para>
/// When this flag is set, CDATA marked
///     sections are not passed literally to the @passthrough function of
///     the parser. Instead, the content of the section (without the
///     `&amp;lt;![CDATA[` and `]]&amp;gt;`) is
///     passed to the @text function. This flag was added in GLib 2.12
/// </para>
/// </summary>

	G_MARKUP_TREAT_CDATA_AS_TEXT = 2,
/// <summary>
/// <para>
/// Normally errors caught by GMarkup
///     itself have line/column information prefixed to them to let the
///     caller know the location of the error. When this flag is set the
///     location information is also prefixed to errors generated by the
///     #GMarkupParser implementation functions
/// </para>
/// </summary>

	G_MARKUP_PREFIX_ERROR_POSITION = 4,
/// <summary>
/// <para>
/// Ignore (don&apos;t report) qualified
///     attributes and tags, along with their contents.  A qualified
///     attribute or tag is one that contains &apos;:&apos; in its name (ie: is in
///     another namespace).  Since: 2.40.
/// </para>
/// </summary>

	G_MARKUP_IGNORE_QUALIFIED = 8
}
