namespace MentorLake.GLib;

[Flags]
public enum GOptionArg
{
	G_OPTION_ARG_NONE = 0,
	G_OPTION_ARG_STRING = 1,
	G_OPTION_ARG_INT = 2,
	G_OPTION_ARG_CALLBACK = 3,
	G_OPTION_ARG_FILENAME = 4,
	G_OPTION_ARG_STRING_ARRAY = 5,
	G_OPTION_ARG_FILENAME_ARRAY = 6,
	G_OPTION_ARG_DOUBLE = 7,
	G_OPTION_ARG_INT64 = 8
}
