namespace MentorLake.GLib;

[Flags]
public enum GSpawnError
{
	G_SPAWN_ERROR_FORK = 0,
	G_SPAWN_ERROR_READ = 1,
	G_SPAWN_ERROR_CHDIR = 2,
	G_SPAWN_ERROR_ACCES = 3,
	G_SPAWN_ERROR_PERM = 4,
	G_SPAWN_ERROR_TOO_BIG = 5,
	G_SPAWN_ERROR_2BIG = 5,
	G_SPAWN_ERROR_NOEXEC = 6,
	G_SPAWN_ERROR_NAMETOOLONG = 7,
	G_SPAWN_ERROR_NOENT = 8,
	G_SPAWN_ERROR_NOMEM = 9,
	G_SPAWN_ERROR_NOTDIR = 10,
	G_SPAWN_ERROR_LOOP = 11,
	G_SPAWN_ERROR_TXTBUSY = 12,
	G_SPAWN_ERROR_IO = 13,
	G_SPAWN_ERROR_NFILE = 14,
	G_SPAWN_ERROR_MFILE = 15,
	G_SPAWN_ERROR_INVAL = 16,
	G_SPAWN_ERROR_ISDIR = 17,
	G_SPAWN_ERROR_LIBBAD = 18,
	G_SPAWN_ERROR_FAILED = 19
}
