namespace MentorLake.GLib;

[Flags]
public enum GTestSubprocessFlags : long
{
	G_TEST_SUBPROCESS_DEFAULT = 0,
	G_TEST_SUBPROCESS_INHERIT_STDIN = 1,
	G_TEST_SUBPROCESS_INHERIT_STDOUT = 2,
	G_TEST_SUBPROCESS_INHERIT_STDERR = 4
}
