namespace MentorLake.GLib;

[Flags]
public enum GUriError
{
	G_URI_ERROR_FAILED = 0,
	G_URI_ERROR_BAD_SCHEME = 1,
	G_URI_ERROR_BAD_USER = 2,
	G_URI_ERROR_BAD_PASSWORD = 3,
	G_URI_ERROR_BAD_AUTH_PARAMS = 4,
	G_URI_ERROR_BAD_HOST = 5,
	G_URI_ERROR_BAD_PORT = 6,
	G_URI_ERROR_BAD_PATH = 7,
	G_URI_ERROR_BAD_QUERY = 8,
	G_URI_ERROR_BAD_FRAGMENT = 9
}
