namespace MentorLake.GLib;

[Flags]
public enum GUserDirectory
{
	G_USER_DIRECTORY_DESKTOP = 0,
	G_USER_DIRECTORY_DOCUMENTS = 1,
	G_USER_DIRECTORY_DOWNLOAD = 2,
	G_USER_DIRECTORY_MUSIC = 3,
	G_USER_DIRECTORY_PICTURES = 4,
	G_USER_DIRECTORY_PUBLIC_SHARE = 5,
	G_USER_DIRECTORY_TEMPLATES = 6,
	G_USER_DIRECTORY_VIDEOS = 7,
	G_USER_N_DIRECTORIES = 8
}
