namespace MentorLake.GLib;

[Flags]
public enum GVariantParseError
{
	G_VARIANT_PARSE_ERROR_FAILED = 0,
	G_VARIANT_PARSE_ERROR_BASIC_TYPE_EXPECTED = 1,
	G_VARIANT_PARSE_ERROR_CANNOT_INFER_TYPE = 2,
	G_VARIANT_PARSE_ERROR_DEFINITE_TYPE_EXPECTED = 3,
	G_VARIANT_PARSE_ERROR_INPUT_NOT_AT_END = 4,
	G_VARIANT_PARSE_ERROR_INVALID_CHARACTER = 5,
	G_VARIANT_PARSE_ERROR_INVALID_FORMAT_STRING = 6,
	G_VARIANT_PARSE_ERROR_INVALID_OBJECT_PATH = 7,
	G_VARIANT_PARSE_ERROR_INVALID_SIGNATURE = 8,
	G_VARIANT_PARSE_ERROR_INVALID_TYPE_STRING = 9,
	G_VARIANT_PARSE_ERROR_NO_COMMON_TYPE = 10,
	G_VARIANT_PARSE_ERROR_NUMBER_OUT_OF_RANGE = 11,
	G_VARIANT_PARSE_ERROR_NUMBER_TOO_BIG = 12,
	G_VARIANT_PARSE_ERROR_TYPE_ERROR = 13,
	G_VARIANT_PARSE_ERROR_UNEXPECTED_TOKEN = 14,
	G_VARIANT_PARSE_ERROR_UNKNOWN_KEYWORD = 15,
	G_VARIANT_PARSE_ERROR_UNTERMINATED_STRING_CONSTANT = 16,
	G_VARIANT_PARSE_ERROR_VALUE_EXPECTED = 17,
	G_VARIANT_PARSE_ERROR_RECURSION = 18
}
