namespace MentorLake.Gtk3.Gtk3;

public enum GtkCssProviderError
{
	GTK_CSS_PROVIDER_ERROR_FAILED,
	GTK_CSS_PROVIDER_ERROR_SYNTAX,
	GTK_CSS_PROVIDER_ERROR_IMPORT,
	GTK_CSS_PROVIDER_ERROR_NAME,
	GTK_CSS_PROVIDER_ERROR_DEPRECATED,
	GTK_CSS_PROVIDER_ERROR_UNKNOWN_VALUE
}
