namespace MentorLake.Gtk3.Gtk3;

public enum GtkCssSectionType
{
	GTK_CSS_SECTION_DOCUMENT,
	GTK_CSS_SECTION_IMPORT,
	GTK_CSS_SECTION_COLOR_DEFINITION,
	GTK_CSS_SECTION_BINDING_SET,
	GTK_CSS_SECTION_RULESET,
	GTK_CSS_SECTION_SELECTOR,
	GTK_CSS_SECTION_DECLARATION,
	GTK_CSS_SECTION_VALUE,
	GTK_CSS_SECTION_KEYFRAMES
}
