namespace MentorLake.Gtk3.Gtk3;

public enum GtkDragResult
{
	GTK_DRAG_RESULT_SUCCESS,
	GTK_DRAG_RESULT_NO_TARGET,
	GTK_DRAG_RESULT_USER_CANCELLED,
	GTK_DRAG_RESULT_TIMEOUT_EXPIRED,
	GTK_DRAG_RESULT_GRAB_BROKEN,
	GTK_DRAG_RESULT_ERROR
}
