namespace MentorLake.Gtk3.Gtk3;

[Flags]
public enum GtkFontChooserLevel
{
	GTK_FONT_CHOOSER_LEVEL_FAMILY = 0,
	GTK_FONT_CHOOSER_LEVEL_STYLE = 1,
	GTK_FONT_CHOOSER_LEVEL_SIZE = 2,
	GTK_FONT_CHOOSER_LEVEL_VARIATIONS = 4,
	GTK_FONT_CHOOSER_LEVEL_FEATURES = 8
}
