namespace MentorLake.Gtk3.Gtk3;

public enum GtkIconSize
{
	GTK_ICON_SIZE_INVALID,
	GTK_ICON_SIZE_MENU,
	GTK_ICON_SIZE_SMALL_TOOLBAR,
	GTK_ICON_SIZE_LARGE_TOOLBAR,
	GTK_ICON_SIZE_BUTTON,
	GTK_ICON_SIZE_DND,
	GTK_ICON_SIZE_DIALOG
}
