namespace MentorLake.Gtk3.Gtk3;

[Flags]
public enum GtkIconLookupFlags
{
	GTK_ICON_LOOKUP_NO_SVG = 0,
	GTK_ICON_LOOKUP_FORCE_SVG = 1,
	GTK_ICON_LOOKUP_USE_BUILTIN = 2,
	GTK_ICON_LOOKUP_GENERIC_FALLBACK = 4,
	GTK_ICON_LOOKUP_FORCE_SIZE = 8,
	GTK_ICON_LOOKUP_FORCE_REGULAR = 16,
	GTK_ICON_LOOKUP_FORCE_SYMBOLIC = 32,
	GTK_ICON_LOOKUP_DIR_LTR = 64,
	GTK_ICON_LOOKUP_DIR_RTL = 128
}
