namespace MentorLake.Gtk3.Gtk3;

[Flags]
public enum GtkJunctionSides
{
	GTK_JUNCTION_NONE = 0,
	GTK_JUNCTION_CORNER_TOPLEFT = 1,
	GTK_JUNCTION_CORNER_TOPRIGHT = 2,
	GTK_JUNCTION_CORNER_BOTTOMLEFT = 4,
	GTK_JUNCTION_CORNER_BOTTOMRIGHT = 8,
	GTK_JUNCTION_TOP = 16,
	GTK_JUNCTION_BOTTOM = 32,
	GTK_JUNCTION_LEFT = 64,
	GTK_JUNCTION_RIGHT = 128
}
