namespace MentorLake.Gtk3.Gtk3;

public enum GtkPrintOperationAction
{
	GTK_PRINT_OPERATION_ACTION_PRINT_DIALOG,
	GTK_PRINT_OPERATION_ACTION_PRINT,
	GTK_PRINT_OPERATION_ACTION_PREVIEW,
	GTK_PRINT_OPERATION_ACTION_EXPORT
}
