namespace MentorLake.Gtk3.Gtk3;

public enum GtkPathPriorityType
{
	GTK_PATH_PRIO_LOWEST,
	GTK_PATH_PRIO_GTK,
	GTK_PATH_PRIO_APPLICATION,
	GTK_PATH_PRIO_THEME,
	GTK_PATH_PRIO_RC,
	GTK_PATH_PRIO_HIGHEST
}
