namespace MentorLake.Atk;

[Flags]
public enum AtkLayer
{
	ATK_LAYER_INVALID = 0,
	ATK_LAYER_BACKGROUND = 1,
	ATK_LAYER_CANVAS = 2,
	ATK_LAYER_WIDGET = 3,
	ATK_LAYER_MDI = 4,
	ATK_LAYER_POPUP = 5,
	ATK_LAYER_OVERLAY = 6,
	ATK_LAYER_WINDOW = 7
}
