namespace MentorLake.Gtk3.Atk;

public enum AtkLayer
{
	ATK_LAYER_INVALID,
	ATK_LAYER_BACKGROUND,
	ATK_LAYER_CANVAS,
	ATK_LAYER_WIDGET,
	ATK_LAYER_MDI,
	ATK_LAYER_POPUP,
	ATK_LAYER_OVERLAY,
	ATK_LAYER_WINDOW
}
