namespace MentorLake.Gtk3.Atk;

public enum AtkRelationType
{
	ATK_RELATION_NULL,
	ATK_RELATION_CONTROLLED_BY,
	ATK_RELATION_CONTROLLER_FOR,
	ATK_RELATION_LABEL_FOR,
	ATK_RELATION_LABELLED_BY,
	ATK_RELATION_MEMBER_OF,
	ATK_RELATION_NODE_CHILD_OF,
	ATK_RELATION_FLOWS_TO,
	ATK_RELATION_FLOWS_FROM,
	ATK_RELATION_SUBWINDOW_OF,
	ATK_RELATION_EMBEDS,
	ATK_RELATION_EMBEDDED_BY,
	ATK_RELATION_POPUP_FOR,
	ATK_RELATION_PARENT_WINDOW_OF,
	ATK_RELATION_DESCRIBED_BY,
	ATK_RELATION_DESCRIPTION_FOR,
	ATK_RELATION_NODE_PARENT_OF,
	ATK_RELATION_DETAILS,
	ATK_RELATION_DETAILS_FOR,
	ATK_RELATION_ERROR_MESSAGE,
	ATK_RELATION_ERROR_FOR,
	ATK_RELATION_LAST_DEFINED
}
