namespace MentorLake.Atk;

[Flags]
public enum AtkRelationType
{
	ATK_RELATION_NULL = 0,
	ATK_RELATION_CONTROLLED_BY = 1,
	ATK_RELATION_CONTROLLER_FOR = 2,
	ATK_RELATION_LABEL_FOR = 3,
	ATK_RELATION_LABELLED_BY = 4,
	ATK_RELATION_MEMBER_OF = 5,
	ATK_RELATION_NODE_CHILD_OF = 6,
	ATK_RELATION_FLOWS_TO = 7,
	ATK_RELATION_FLOWS_FROM = 8,
	ATK_RELATION_SUBWINDOW_OF = 9,
	ATK_RELATION_EMBEDS = 10,
	ATK_RELATION_EMBEDDED_BY = 11,
	ATK_RELATION_POPUP_FOR = 12,
	ATK_RELATION_PARENT_WINDOW_OF = 13,
	ATK_RELATION_DESCRIBED_BY = 14,
	ATK_RELATION_DESCRIPTION_FOR = 15,
	ATK_RELATION_NODE_PARENT_OF = 16,
	ATK_RELATION_DETAILS = 17,
	ATK_RELATION_DETAILS_FOR = 18,
	ATK_RELATION_ERROR_MESSAGE = 19,
	ATK_RELATION_ERROR_FOR = 20,
	ATK_RELATION_LAST_DEFINED = 21
}
