namespace MentorLake.Gtk3.Atk;

public enum AtkScrollType
{
	ATK_SCROLL_TOP_LEFT,
	ATK_SCROLL_BOTTOM_RIGHT,
	ATK_SCROLL_TOP_EDGE,
	ATK_SCROLL_BOTTOM_EDGE,
	ATK_SCROLL_LEFT_EDGE,
	ATK_SCROLL_RIGHT_EDGE,
	ATK_SCROLL_ANYWHERE
}
