namespace MentorLake.Atk;

[Flags]
public enum AtkScrollType
{
	ATK_SCROLL_TOP_LEFT = 0,
	ATK_SCROLL_BOTTOM_RIGHT = 1,
	ATK_SCROLL_TOP_EDGE = 2,
	ATK_SCROLL_BOTTOM_EDGE = 3,
	ATK_SCROLL_LEFT_EDGE = 4,
	ATK_SCROLL_RIGHT_EDGE = 5,
	ATK_SCROLL_ANYWHERE = 6
}
