namespace MentorLake.Atk;

[Flags]
public enum AtkTextAttribute
{
	ATK_TEXT_ATTR_INVALID = 0,
	ATK_TEXT_ATTR_LEFT_MARGIN = 1,
	ATK_TEXT_ATTR_RIGHT_MARGIN = 2,
	ATK_TEXT_ATTR_INDENT = 3,
	ATK_TEXT_ATTR_INVISIBLE = 4,
	ATK_TEXT_ATTR_EDITABLE = 5,
	ATK_TEXT_ATTR_PIXELS_ABOVE_LINES = 6,
	ATK_TEXT_ATTR_PIXELS_BELOW_LINES = 7,
	ATK_TEXT_ATTR_PIXELS_INSIDE_WRAP = 8,
	ATK_TEXT_ATTR_BG_FULL_HEIGHT = 9,
	ATK_TEXT_ATTR_RISE = 10,
	ATK_TEXT_ATTR_UNDERLINE = 11,
	ATK_TEXT_ATTR_STRIKETHROUGH = 12,
	ATK_TEXT_ATTR_SIZE = 13,
	ATK_TEXT_ATTR_SCALE = 14,
	ATK_TEXT_ATTR_WEIGHT = 15,
	ATK_TEXT_ATTR_LANGUAGE = 16,
	ATK_TEXT_ATTR_FAMILY_NAME = 17,
	ATK_TEXT_ATTR_BG_COLOR = 18,
	ATK_TEXT_ATTR_FG_COLOR = 19,
	ATK_TEXT_ATTR_BG_STIPPLE = 20,
	ATK_TEXT_ATTR_FG_STIPPLE = 21,
	ATK_TEXT_ATTR_WRAP_MODE = 22,
	ATK_TEXT_ATTR_DIRECTION = 23,
	ATK_TEXT_ATTR_JUSTIFICATION = 24,
	ATK_TEXT_ATTR_STRETCH = 25,
	ATK_TEXT_ATTR_VARIANT = 26,
	ATK_TEXT_ATTR_STYLE = 27,
	ATK_TEXT_ATTR_TEXT_POSITION = 28,
	ATK_TEXT_ATTR_LAST_DEFINED = 29
}
