namespace MentorLake.Gtk3.Atk;

public enum AtkTextBoundary
{
	ATK_TEXT_BOUNDARY_CHAR,
	ATK_TEXT_BOUNDARY_WORD_START,
	ATK_TEXT_BOUNDARY_WORD_END,
	ATK_TEXT_BOUNDARY_SENTENCE_START,
	ATK_TEXT_BOUNDARY_SENTENCE_END,
	ATK_TEXT_BOUNDARY_LINE_START,
	ATK_TEXT_BOUNDARY_LINE_END
}
