namespace MentorLake.Gtk3.Atk;

public enum AtkTextGranularity
{
	ATK_TEXT_GRANULARITY_CHAR,
	ATK_TEXT_GRANULARITY_WORD,
	ATK_TEXT_GRANULARITY_SENTENCE,
	ATK_TEXT_GRANULARITY_LINE,
	ATK_TEXT_GRANULARITY_PARAGRAPH
}
