namespace MentorLake.Gtk3.Atk;

public enum AtkValueType
{
	ATK_VALUE_VERY_WEAK,
	ATK_VALUE_WEAK,
	ATK_VALUE_ACCEPTABLE,
	ATK_VALUE_STRONG,
	ATK_VALUE_VERY_STRONG,
	ATK_VALUE_VERY_LOW,
	ATK_VALUE_LOW,
	ATK_VALUE_MEDIUM,
	ATK_VALUE_HIGH,
	ATK_VALUE_VERY_HIGH,
	ATK_VALUE_VERY_BAD,
	ATK_VALUE_BAD,
	ATK_VALUE_GOOD,
	ATK_VALUE_VERY_GOOD,
	ATK_VALUE_BEST,
	ATK_VALUE_LAST_DEFINED
}
