namespace MentorLake.GObject;

[Flags]
public enum GParamFlags : uint
{
	G_PARAM_READABLE = 1,
	G_PARAM_WRITABLE = 2,
	G_PARAM_READWRITE = 3,
	G_PARAM_CONSTRUCT = 4,
	G_PARAM_CONSTRUCT_ONLY = 8,
	G_PARAM_LAX_VALIDATION = 16,
	G_PARAM_STATIC_NAME = 32,
	G_PARAM_PRIVATE = 32,
	G_PARAM_STATIC_NICK = 64,
	G_PARAM_STATIC_BLURB = 128,
	G_PARAM_EXPLICIT_NOTIFY = 1073741824,
	G_PARAM_DEPRECATED = 2147483648
}
