namespace MentorLake.Pango;

[Flags]
public enum PangoUnderline
{
	PANGO_UNDERLINE_NONE = 0,
	PANGO_UNDERLINE_SINGLE = 1,
	PANGO_UNDERLINE_DOUBLE = 2,
	PANGO_UNDERLINE_LOW = 3,
	PANGO_UNDERLINE_ERROR = 4,
	PANGO_UNDERLINE_SINGLE_LINE = 5,
	PANGO_UNDERLINE_DOUBLE_LINE = 6,
	PANGO_UNDERLINE_ERROR_LINE = 7
}
