namespace MentorLake.Pango;

[Flags]
public enum PangoVariant
{
	PANGO_VARIANT_NORMAL = 0,
	PANGO_VARIANT_SMALL_CAPS = 1,
	PANGO_VARIANT_ALL_SMALL_CAPS = 2,
	PANGO_VARIANT_PETITE_CAPS = 3,
	PANGO_VARIANT_ALL_PETITE_CAPS = 4,
	PANGO_VARIANT_UNICASE = 5,
	PANGO_VARIANT_TITLE_CAPS = 6
}
