namespace MentorLake.Pango;

[Flags]
public enum PangoFontMask : uint
{
	PANGO_FONT_MASK_FAMILY = 1,
	PANGO_FONT_MASK_STYLE = 2,
	PANGO_FONT_MASK_VARIANT = 4,
	PANGO_FONT_MASK_WEIGHT = 8,
	PANGO_FONT_MASK_STRETCH = 16,
	PANGO_FONT_MASK_SIZE = 32,
	PANGO_FONT_MASK_GRAVITY = 64,
	PANGO_FONT_MASK_VARIATIONS = 128,
	PANGO_FONT_MASK_FEATURES = 256
}
