namespace MentorLake.Pango;

[Flags]
public enum PangoLayoutDeserializeError
{
	PANGO_LAYOUT_DESERIALIZE_INVALID = 0,
	PANGO_LAYOUT_DESERIALIZE_INVALID_VALUE = 1,
	PANGO_LAYOUT_DESERIALIZE_MISSING_VALUE = 2
}
