namespace MentorLake.Pango;

[Flags]
public enum PangoBidiType
{
	PANGO_BIDI_TYPE_L = 0,
	PANGO_BIDI_TYPE_LRE = 1,
	PANGO_BIDI_TYPE_LRO = 2,
	PANGO_BIDI_TYPE_R = 3,
	PANGO_BIDI_TYPE_AL = 4,
	PANGO_BIDI_TYPE_RLE = 5,
	PANGO_BIDI_TYPE_RLO = 6,
	PANGO_BIDI_TYPE_PDF = 7,
	PANGO_BIDI_TYPE_EN = 8,
	PANGO_BIDI_TYPE_ES = 9,
	PANGO_BIDI_TYPE_ET = 10,
	PANGO_BIDI_TYPE_AN = 11,
	PANGO_BIDI_TYPE_CS = 12,
	PANGO_BIDI_TYPE_NSM = 13,
	PANGO_BIDI_TYPE_BN = 14,
	PANGO_BIDI_TYPE_B = 15,
	PANGO_BIDI_TYPE_S = 16,
	PANGO_BIDI_TYPE_WS = 17,
	PANGO_BIDI_TYPE_ON = 18,
	PANGO_BIDI_TYPE_LRI = 19,
	PANGO_BIDI_TYPE_RLI = 20,
	PANGO_BIDI_TYPE_FSI = 21,
	PANGO_BIDI_TYPE_PDI = 22
}
