namespace MentorLake.Pango;

[Flags]
public enum PangoTextTransform
{
	PANGO_TEXT_TRANSFORM_NONE = 0,
	PANGO_TEXT_TRANSFORM_LOWERCASE = 1,
	PANGO_TEXT_TRANSFORM_UPPERCASE = 2,
	PANGO_TEXT_TRANSFORM_CAPITALIZE = 3
}
