namespace MentorLake.Pango;

[Flags]
public enum PangoRenderPart
{
	PANGO_RENDER_PART_FOREGROUND = 0,
	PANGO_RENDER_PART_BACKGROUND = 1,
	PANGO_RENDER_PART_UNDERLINE = 2,
	PANGO_RENDER_PART_STRIKETHROUGH = 3,
	PANGO_RENDER_PART_OVERLINE = 4
}
