namespace MentorLake.Gio;

[Flags]
public enum GCredentialsType
{
	G_CREDENTIALS_TYPE_INVALID = 0,
	G_CREDENTIALS_TYPE_LINUX_UCRED = 1,
	G_CREDENTIALS_TYPE_FREEBSD_CMSGCRED = 2,
	G_CREDENTIALS_TYPE_OPENBSD_SOCKPEERCRED = 3,
	G_CREDENTIALS_TYPE_SOLARIS_UCRED = 4,
	G_CREDENTIALS_TYPE_NETBSD_UNPCBID = 5,
	G_CREDENTIALS_TYPE_APPLE_XUCRED = 6,
	G_CREDENTIALS_TYPE_WIN32_PID = 7
}
