namespace MentorLake.Gio;

[Flags]
public enum GDataStreamByteOrder
{
	G_DATA_STREAM_BYTE_ORDER_BIG_ENDIAN = 0,
	G_DATA_STREAM_BYTE_ORDER_LITTLE_ENDIAN = 1,
	G_DATA_STREAM_BYTE_ORDER_HOST_ENDIAN = 2
}
