namespace MentorLake.Gio;

[Flags]
public enum GDataStreamNewlineType
{
	G_DATA_STREAM_NEWLINE_TYPE_LF = 0,
	G_DATA_STREAM_NEWLINE_TYPE_CR = 1,
	G_DATA_STREAM_NEWLINE_TYPE_CR_LF = 2,
	G_DATA_STREAM_NEWLINE_TYPE_ANY = 3
}
