namespace MentorLake.Gio;

[Flags]
public enum GDBusMessageHeaderField
{
	G_DBUS_MESSAGE_HEADER_FIELD_INVALID = 0,
	G_DBUS_MESSAGE_HEADER_FIELD_PATH = 1,
	G_DBUS_MESSAGE_HEADER_FIELD_INTERFACE = 2,
	G_DBUS_MESSAGE_HEADER_FIELD_MEMBER = 3,
	G_DBUS_MESSAGE_HEADER_FIELD_ERROR_NAME = 4,
	G_DBUS_MESSAGE_HEADER_FIELD_REPLY_SERIAL = 5,
	G_DBUS_MESSAGE_HEADER_FIELD_DESTINATION = 6,
	G_DBUS_MESSAGE_HEADER_FIELD_SENDER = 7,
	G_DBUS_MESSAGE_HEADER_FIELD_SIGNATURE = 8,
	G_DBUS_MESSAGE_HEADER_FIELD_NUM_UNIX_FDS = 9
}
