namespace MentorLake.Gio;

[Flags]
public enum GDBusMessageType
{
	G_DBUS_MESSAGE_TYPE_INVALID = 0,
	G_DBUS_MESSAGE_TYPE_METHOD_CALL = 1,
	G_DBUS_MESSAGE_TYPE_METHOD_RETURN = 2,
	G_DBUS_MESSAGE_TYPE_ERROR = 3,
	G_DBUS_MESSAGE_TYPE_SIGNAL = 4
}
