namespace MentorLake.Gio;

[Flags]
public enum GDriveStartStopType
{
	G_DRIVE_START_STOP_TYPE_UNKNOWN = 0,
	G_DRIVE_START_STOP_TYPE_SHUTDOWN = 1,
	G_DRIVE_START_STOP_TYPE_NETWORK = 2,
	G_DRIVE_START_STOP_TYPE_MULTIDISK = 3,
	G_DRIVE_START_STOP_TYPE_PASSWORD = 4
}
