namespace MentorLake.Gio;

[Flags]
public enum GFileMonitorEvent
{
	G_FILE_MONITOR_EVENT_CHANGED = 0,
	G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT = 1,
	G_FILE_MONITOR_EVENT_DELETED = 2,
	G_FILE_MONITOR_EVENT_CREATED = 3,
	G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED = 4,
	G_FILE_MONITOR_EVENT_PRE_UNMOUNT = 5,
	G_FILE_MONITOR_EVENT_UNMOUNTED = 6,
	G_FILE_MONITOR_EVENT_MOVED = 7,
	G_FILE_MONITOR_EVENT_RENAMED = 8,
	G_FILE_MONITOR_EVENT_MOVED_IN = 9,
	G_FILE_MONITOR_EVENT_MOVED_OUT = 10
}
