namespace MentorLake.Gio;

[Flags]
public enum GFileType
{
	G_FILE_TYPE_UNKNOWN = 0,
	G_FILE_TYPE_REGULAR = 1,
	G_FILE_TYPE_DIRECTORY = 2,
	G_FILE_TYPE_SYMBOLIC_LINK = 3,
	G_FILE_TYPE_SPECIAL = 4,
	G_FILE_TYPE_SHORTCUT = 5,
	G_FILE_TYPE_MOUNTABLE = 6
}
