namespace MentorLake.Gio;

[Flags]
public enum GFileAttributeType
{
	G_FILE_ATTRIBUTE_TYPE_INVALID = 0,
	G_FILE_ATTRIBUTE_TYPE_STRING = 1,
	G_FILE_ATTRIBUTE_TYPE_BYTE_STRING = 2,
	G_FILE_ATTRIBUTE_TYPE_BOOLEAN = 3,
	G_FILE_ATTRIBUTE_TYPE_UINT32 = 4,
	G_FILE_ATTRIBUTE_TYPE_INT32 = 5,
	G_FILE_ATTRIBUTE_TYPE_UINT64 = 6,
	G_FILE_ATTRIBUTE_TYPE_INT64 = 7,
	G_FILE_ATTRIBUTE_TYPE_OBJECT = 8,
	G_FILE_ATTRIBUTE_TYPE_STRINGV = 9
}
