namespace MentorLake.Gio;

[Flags]
public enum GMemoryMonitorWarningLevel
{
	G_MEMORY_MONITOR_WARNING_LEVEL_LOW = 50,
	G_MEMORY_MONITOR_WARNING_LEVEL_MEDIUM = 100,
	G_MEMORY_MONITOR_WARNING_LEVEL_CRITICAL = 255
}
