namespace MentorLake.Gio;

[Flags]
public enum GNetworkConnectivity
{
	G_NETWORK_CONNECTIVITY_LOCAL = 1,
	G_NETWORK_CONNECTIVITY_LIMITED = 2,
	G_NETWORK_CONNECTIVITY_PORTAL = 3,
	G_NETWORK_CONNECTIVITY_FULL = 4
}
