namespace MentorLake.Gio;

[Flags]
public enum GNotificationPriority
{
	G_NOTIFICATION_PRIORITY_NORMAL = 0,
	G_NOTIFICATION_PRIORITY_LOW = 1,
	G_NOTIFICATION_PRIORITY_HIGH = 2,
	G_NOTIFICATION_PRIORITY_URGENT = 3
}
