namespace MentorLake.Gio;

[Flags]
public enum GSettingsBindFlags : long
{
	G_SETTINGS_BIND_DEFAULT = 0,
	G_SETTINGS_BIND_GET = 1,
	G_SETTINGS_BIND_SET = 2,
	G_SETTINGS_BIND_NO_SENSITIVITY = 4,
	G_SETTINGS_BIND_GET_NO_CHANGES = 8,
	G_SETTINGS_BIND_INVERT_BOOLEAN = 16
}
