namespace MentorLake.Gio;

[Flags]
public enum GSocketClientEvent
{
	G_SOCKET_CLIENT_RESOLVING = 0,
	G_SOCKET_CLIENT_RESOLVED = 1,
	G_SOCKET_CLIENT_CONNECTING = 2,
	G_SOCKET_CLIENT_CONNECTED = 3,
	G_SOCKET_CLIENT_PROXY_NEGOTIATING = 4,
	G_SOCKET_CLIENT_PROXY_NEGOTIATED = 5,
	G_SOCKET_CLIENT_TLS_HANDSHAKING = 6,
	G_SOCKET_CLIENT_TLS_HANDSHAKED = 7,
	G_SOCKET_CLIENT_COMPLETE = 8
}
