namespace MentorLake.Gio;

[Flags]
public enum GTlsProtocolVersion
{
	G_TLS_PROTOCOL_VERSION_UNKNOWN = 0,
	G_TLS_PROTOCOL_VERSION_SSL_3_0 = 1,
	G_TLS_PROTOCOL_VERSION_TLS_1_0 = 2,
	G_TLS_PROTOCOL_VERSION_TLS_1_1 = 3,
	G_TLS_PROTOCOL_VERSION_TLS_1_2 = 4,
	G_TLS_PROTOCOL_VERSION_TLS_1_3 = 5,
	G_TLS_PROTOCOL_VERSION_DTLS_1_0 = 201,
	G_TLS_PROTOCOL_VERSION_DTLS_1_2 = 202
}
