namespace MentorLake.Gio;

[Flags]
public enum GTlsError
{
	G_TLS_ERROR_UNAVAILABLE = 0,
	G_TLS_ERROR_MISC = 1,
	G_TLS_ERROR_BAD_CERTIFICATE = 2,
	G_TLS_ERROR_NOT_TLS = 3,
	G_TLS_ERROR_HANDSHAKE = 4,
	G_TLS_ERROR_CERTIFICATE_REQUIRED = 5,
	G_TLS_ERROR_EOF = 6,
	G_TLS_ERROR_INAPPROPRIATE_FALLBACK = 7,
	G_TLS_ERROR_BAD_CERTIFICATE_PASSWORD = 8
}
