namespace MentorLake.Gio;

[Flags]
public enum GTlsChannelBindingError
{
	G_TLS_CHANNEL_BINDING_ERROR_NOT_IMPLEMENTED = 0,
	G_TLS_CHANNEL_BINDING_ERROR_INVALID_STATE = 1,
	G_TLS_CHANNEL_BINDING_ERROR_NOT_AVAILABLE = 2,
	G_TLS_CHANNEL_BINDING_ERROR_NOT_SUPPORTED = 3,
	G_TLS_CHANNEL_BINDING_ERROR_GENERAL_ERROR = 4
}
