namespace MentorLake.Gio;

[Flags]
public enum GTlsChannelBindingType
{
	G_TLS_CHANNEL_BINDING_TLS_UNIQUE = 0,
	G_TLS_CHANNEL_BINDING_TLS_SERVER_END_POINT = 1,
	G_TLS_CHANNEL_BINDING_TLS_EXPORTER = 2
}
