namespace MentorLake.Gio;

[Flags]
public enum GTlsPasswordFlags : long
{
	G_TLS_PASSWORD_NONE = 0,
	G_TLS_PASSWORD_RETRY = 2,
	G_TLS_PASSWORD_MANY_TRIES = 4,
	G_TLS_PASSWORD_FINAL_TRY = 8,
	G_TLS_PASSWORD_PKCS11_USER = 16,
	G_TLS_PASSWORD_PKCS11_SECURITY_OFFICER = 32,
	G_TLS_PASSWORD_PKCS11_CONTEXT_SPECIFIC = 64
}
