namespace MentorLake.Gio;

[Flags]
public enum GUnixSocketAddressType
{
	G_UNIX_SOCKET_ADDRESS_INVALID = 0,
	G_UNIX_SOCKET_ADDRESS_ANONYMOUS = 1,
	G_UNIX_SOCKET_ADDRESS_PATH = 2,
	G_UNIX_SOCKET_ADDRESS_ABSTRACT = 3,
	G_UNIX_SOCKET_ADDRESS_ABSTRACT_PADDED = 4
}
