namespace MentorLake.Gdk;

[Flags]
public enum GdkAxisFlags : uint
{
	GDK_AXIS_FLAG_X = 2,
	GDK_AXIS_FLAG_Y = 4,
	GDK_AXIS_FLAG_PRESSURE = 8,
	GDK_AXIS_FLAG_XTILT = 16,
	GDK_AXIS_FLAG_YTILT = 32,
	GDK_AXIS_FLAG_WHEEL = 64,
	GDK_AXIS_FLAG_DISTANCE = 128,
	GDK_AXIS_FLAG_ROTATION = 256,
	GDK_AXIS_FLAG_SLIDER = 512
}
