namespace MentorLake.Gdk;

[Flags]
public enum GdkDeviceToolType
{
	GDK_DEVICE_TOOL_TYPE_UNKNOWN = 0,
	GDK_DEVICE_TOOL_TYPE_PEN = 1,
	GDK_DEVICE_TOOL_TYPE_ERASER = 2,
	GDK_DEVICE_TOOL_TYPE_BRUSH = 3,
	GDK_DEVICE_TOOL_TYPE_PENCIL = 4,
	GDK_DEVICE_TOOL_TYPE_AIRBRUSH = 5,
	GDK_DEVICE_TOOL_TYPE_MOUSE = 6,
	GDK_DEVICE_TOOL_TYPE_LENS = 7
}
