namespace MentorLake.Gdk;

[Flags]
public enum GdkDragProtocol
{
	GDK_DRAG_PROTO_NONE = 0,
	GDK_DRAG_PROTO_MOTIF = 1,
	GDK_DRAG_PROTO_XDND = 2,
	GDK_DRAG_PROTO_ROOTWIN = 3,
	GDK_DRAG_PROTO_WIN32_DROPFILES = 4,
	GDK_DRAG_PROTO_OLE2 = 5,
	GDK_DRAG_PROTO_LOCAL = 6,
	GDK_DRAG_PROTO_WAYLAND = 7
}
