namespace MentorLake.Gdk;

[Flags]
public enum GdkFrameClockPhase : uint
{
	GDK_FRAME_CLOCK_PHASE_NONE = 0,
	GDK_FRAME_CLOCK_PHASE_FLUSH_EVENTS = 1,
	GDK_FRAME_CLOCK_PHASE_BEFORE_PAINT = 2,
	GDK_FRAME_CLOCK_PHASE_UPDATE = 4,
	GDK_FRAME_CLOCK_PHASE_LAYOUT = 8,
	GDK_FRAME_CLOCK_PHASE_PAINT = 16,
	GDK_FRAME_CLOCK_PHASE_RESUME_EVENTS = 32,
	GDK_FRAME_CLOCK_PHASE_AFTER_PAINT = 64
}
