namespace MentorLake.Gdk;

[Flags]
public enum GdkInputSource
{
	GDK_SOURCE_MOUSE = 0,
	GDK_SOURCE_PEN = 1,
	GDK_SOURCE_ERASER = 2,
	GDK_SOURCE_CURSOR = 3,
	GDK_SOURCE_KEYBOARD = 4,
	GDK_SOURCE_TOUCHSCREEN = 5,
	GDK_SOURCE_TOUCHPAD = 6,
	GDK_SOURCE_TRACKPOINT = 7,
	GDK_SOURCE_TABLET_PAD = 8
}
