namespace MentorLake.Gdk;

[Flags]
public enum GdkModifierIntent
{
	GDK_MODIFIER_INTENT_PRIMARY_ACCELERATOR = 0,
	GDK_MODIFIER_INTENT_CONTEXT_MENU = 1,
	GDK_MODIFIER_INTENT_EXTEND_SELECTION = 2,
	GDK_MODIFIER_INTENT_MODIFY_SELECTION = 3,
	GDK_MODIFIER_INTENT_NO_TEXT_INPUT = 4,
	GDK_MODIFIER_INTENT_SHIFT_GROUP = 5,
	GDK_MODIFIER_INTENT_DEFAULT_MOD_MASK = 6
}
