namespace MentorLake.Gdk;

[Flags]
public enum GdkSeatCapabilities : uint
{
	GDK_SEAT_CAPABILITY_NONE = 0,
	GDK_SEAT_CAPABILITY_POINTER = 1,
	GDK_SEAT_CAPABILITY_TOUCH = 2,
	GDK_SEAT_CAPABILITY_TABLET_STYLUS = 4,
	GDK_SEAT_CAPABILITY_KEYBOARD = 8,
	GDK_SEAT_CAPABILITY_ALL_POINTING = 7,
	GDK_SEAT_CAPABILITY_ALL = 15
}
