namespace MentorLake.Gdk;

[Flags]
public enum GdkSubpixelLayout
{
	GDK_SUBPIXEL_LAYOUT_UNKNOWN = 0,
	GDK_SUBPIXEL_LAYOUT_NONE = 1,
	GDK_SUBPIXEL_LAYOUT_HORIZONTAL_RGB = 2,
	GDK_SUBPIXEL_LAYOUT_HORIZONTAL_BGR = 3,
	GDK_SUBPIXEL_LAYOUT_VERTICAL_RGB = 4,
	GDK_SUBPIXEL_LAYOUT_VERTICAL_BGR = 5
}
