namespace MentorLake.Gdk;

[Flags]
public enum GdkTouchpadGesturePhase
{
	GDK_TOUCHPAD_GESTURE_PHASE_BEGIN = 0,
	GDK_TOUCHPAD_GESTURE_PHASE_UPDATE = 1,
	GDK_TOUCHPAD_GESTURE_PHASE_END = 2,
	GDK_TOUCHPAD_GESTURE_PHASE_CANCEL = 3
}
