namespace MentorLake.Gdk;

[Flags]
public enum GdkWindowEdge
{
	GDK_WINDOW_EDGE_NORTH_WEST = 0,
	GDK_WINDOW_EDGE_NORTH = 1,
	GDK_WINDOW_EDGE_NORTH_EAST = 2,
	GDK_WINDOW_EDGE_WEST = 3,
	GDK_WINDOW_EDGE_EAST = 4,
	GDK_WINDOW_EDGE_SOUTH_WEST = 5,
	GDK_WINDOW_EDGE_SOUTH = 6,
	GDK_WINDOW_EDGE_SOUTH_EAST = 7
}
