namespace MentorLake.Gdk;

[Flags]
public enum GdkWindowTypeHint
{
	GDK_WINDOW_TYPE_HINT_NORMAL = 0,
	GDK_WINDOW_TYPE_HINT_DIALOG = 1,
	GDK_WINDOW_TYPE_HINT_MENU = 2,
	GDK_WINDOW_TYPE_HINT_TOOLBAR = 3,
	GDK_WINDOW_TYPE_HINT_SPLASHSCREEN = 4,
	GDK_WINDOW_TYPE_HINT_UTILITY = 5,
	GDK_WINDOW_TYPE_HINT_DOCK = 6,
	GDK_WINDOW_TYPE_HINT_DESKTOP = 7,
	GDK_WINDOW_TYPE_HINT_DROPDOWN_MENU = 8,
	GDK_WINDOW_TYPE_HINT_POPUP_MENU = 9,
	GDK_WINDOW_TYPE_HINT_TOOLTIP = 10,
	GDK_WINDOW_TYPE_HINT_NOTIFICATION = 11,
	GDK_WINDOW_TYPE_HINT_COMBO = 12,
	GDK_WINDOW_TYPE_HINT_DND = 13
}
